### ISSUE TITLE
Send tweet

### ISSUE THREAD

**Issue by DigItalWarrior69** [alperensert/twitter-curl-login#1]
Hello, I'm try your script and login work as I expect.
How I can tweet a message via CURL after login?

**Comment by alperensert-zz** [comment]
Firstly, you need a cookie file for login your twitter account. You can create with docs. 
Secondly, include your cookie with curl. 
Referer info: **twitter.com**
Url: _https://twitter.com/i/tweet/create_
Method: **POST**
Postfields: _?authenticity_token=xxx&is_permalink_page:false&status: yourstatue_

You need authenticity token, u can find him with **ara** function :)
